go:
  version: 1.13
  cgo: false
repository:
    path: github.com/treydock/check_mount_exporter
build:
    binaries:
        - name: check_mount_exporter
          path: .
    flags: -a -tags netgo
    ldflags: |
        -extldflags "-static"
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - CHANGELOG.md
