---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.4.0

executors:
  # Whenever the Go version is updated here, .promu.yml should
  # also be updated.
  golang:
    docker:
    - image: circleci/golang:1.13

jobs:
  test:
    executor: golang
    steps:
    - prometheus/setup_environment
    - run: make
    - prometheus/store_artifact:
        file: check_mount_exporter
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build
    - run: 
        command: |
          if [ -n "$CIRCLE_TAG" ]; then
            make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
          else
            make docker
          fi
workflows:
  version: 2
  check_mount_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - prometheus/publis_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publis_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v([0-9]).*/
          branches:
            ignore: /.*/
